2022-06-16 21:00:13,393 INFO     task_3_client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777
2022-06-16 21:00:13,394 DEBUG    task_3_client.py Разбор сообщения от сервера: {'response': 200}
2022-06-16 21:00:13,394 INFO     task_3_client.py Принят ответ от сервера 200 : OK
2022-06-20 22:07:09,217 DEBUG    log_decorator.py Была вызвана функция create_arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-20 22:07:09,217 INFO     task_3_client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777
2022-06-20 22:07:09,218 DEBUG    log_decorator.py Была вызвана функция create_presence c параметрами ('LoggedUser',), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-20 22:07:09,219 DEBUG    task_3_client.py Разбор сообщения от сервера: {'response': 200}
2022-06-20 22:07:09,220 DEBUG    log_decorator.py Была вызвана функция process_ans c параметрами ({'response': 200},), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-20 22:07:09,220 INFO     task_3_client.py Принят ответ от сервера 200 : OK
2022-06-20 22:07:09,220 DEBUG    log_decorator.py Была вызвана функция main c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции <module>@@@Вызов из функции <module>@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:24:52,987 DEBUG    log_decorator.py Была вызвана функция create_arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:24:58,942 INFO     task_3_client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777
2022-06-26 19:24:58,943 DEBUG    log_decorator.py Была вызвана функция create_presence c параметрами ('LoggedUser',), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:24:59,452 DEBUG    task_3_client.py Разбор сообщения от сервера: {'response': 200}
2022-06-26 19:24:59,452 DEBUG    log_decorator.py Была вызвана функция process_ans c параметрами ({'response': 200},), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:24:59,453 INFO     task_3_client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-06-26 19:24:59,454 DEBUG    task_3_client.py Запущены процессы
2022-06-26 19:25:18,974 DEBUG    task_3_client.py Сформирован словарь сообщения: {'action': 'message', 'sender': 'LoggedUser', 'to': 'Guest', 'time': 1656260718.973727, 'mess_text': 'Hi'}
2022-06-26 19:25:18,974 INFO     task_3_client.py Отправлено сообщение для пользователя Guest
2022-06-26 19:25:18,982 DEBUG    log_decorator.py Была вызвана функция create_message c параметрами (<socket.socket fd=396, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 53043), raddr=('127.0.0.1', 7777)>, 'LoggedUser'), {}.Вызов из модуля __main__.Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive@@@Вызов из функции user_interactive@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:25:52,180 DEBUG    task_3_client.py Сформирован словарь сообщения: {'action': 'message', 'sender': 'LoggedUser', 'to': 'User', 'time': 1656260752.1803205, 'mess_text': 'Hi'}
2022-06-26 19:25:52,180 INFO     task_3_client.py Отправлено сообщение для пользователя User
2022-06-26 19:25:52,181 DEBUG    log_decorator.py Была вызвана функция create_message c параметрами (<socket.socket fd=396, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 53043), raddr=('127.0.0.1', 7777)>, 'LoggedUser'), {}.Вызов из модуля __main__.Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive@@@Вызов из функции user_interactive@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:36:06,382 DEBUG    log_decorator.py Была вызвана функция create_arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:36:10,738 INFO     task_3_client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777
2022-06-26 19:36:10,739 DEBUG    log_decorator.py Была вызвана функция create_presence c параметрами ('LoggedUser',), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:36:11,251 DEBUG    task_3_client.py Разбор сообщения от сервера: {'response': 200}
2022-06-26 19:36:11,252 DEBUG    log_decorator.py Была вызвана функция process_ans c параметрами ({'response': 200},), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:36:11,252 INFO     task_3_client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-06-26 19:36:11,253 DEBUG    task_3_client.py Запущены процессы
2022-06-26 19:36:21,487 DEBUG    task_3_client.py Сформирован словарь сообщения: {'action': 'message', 'sender': 'LoggedUser', 'to': 'LoggedUser', 'time': 1656261381.4871173, 'mess_text': 'Hi'}
2022-06-26 19:36:21,487 INFO     task_3_client.py Отправлено сообщение для пользователя LoggedUser
2022-06-26 19:36:21,489 DEBUG    log_decorator.py Была вызвана функция create_message c параметрами (<socket.socket fd=464, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 60190), raddr=('127.0.0.1', 7777)>, 'LoggedUser'), {}.Вызов из модуля __main__.Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive@@@Вызов из функции user_interactive@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:36:21,493 CRITICAL task_3_client.py Потеряно соединение с сервером.
2022-06-26 19:36:21,493 DEBUG    log_decorator.py Была вызвана функция message_from_server c параметрами (<socket.socket fd=464, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 60190), raddr=('127.0.0.1', 7777)>, 'LoggedUser'), {}.Вызов из модуля __main__.Вызов из функции self._bootstrap_inner().Вызов из функции run@@@Вызов из функции run@@@вызов из модуля C:\Python\Python39\lib\threading.py
2022-06-26 19:36:22,345 DEBUG    log_decorator.py Была вызвана функция main c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции <module>@@@Вызов из функции <module>@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:36:41,923 DEBUG    log_decorator.py Была вызвана функция create_arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:36:45,537 INFO     task_3_client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777
2022-06-26 19:36:45,538 DEBUG    log_decorator.py Была вызвана функция create_presence c параметрами ('LoggedUser',), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:36:46,047 DEBUG    task_3_client.py Разбор сообщения от сервера: {'response': 200}
2022-06-26 19:36:46,048 DEBUG    log_decorator.py Была вызвана функция process_ans c параметрами ({'response': 200},), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:36:46,048 INFO     task_3_client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-06-26 19:36:46,048 DEBUG    task_3_client.py Запущены процессы
2022-06-26 19:36:56,361 DEBUG    task_3_client.py Сформирован словарь сообщения: {'action': 'message', 'sender': 'Guest', 'to': 'LoggedUser', 'time': 1656261416.361852, 'mess_text': 'Hi'}
2022-06-26 19:36:56,361 INFO     task_3_client.py Отправлено сообщение для пользователя LoggedUser
2022-06-26 19:36:56,362 DEBUG    log_decorator.py Была вызвана функция create_message c параметрами (<socket.socket fd=440, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 54535), raddr=('127.0.0.1', 7777)>, 'Guest'), {}.Вызов из модуля __main__.Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive@@@Вызов из функции user_interactive@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:36:56,822 CRITICAL task_3_client.py Потеряно соединение с сервером.
2022-06-26 19:36:56,822 DEBUG    log_decorator.py Была вызвана функция message_from_server c параметрами (<socket.socket fd=440, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 54535), raddr=('127.0.0.1', 7777)>, 'Guest'), {}.Вызов из модуля __main__.Вызов из функции self._bootstrap_inner().Вызов из функции run@@@Вызов из функции run@@@вызов из модуля C:\Python\Python39\lib\threading.py
2022-06-26 19:36:57,162 DEBUG    log_decorator.py Была вызвана функция main c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции <module>@@@Вызов из функции <module>@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 19:42:55,947 DEBUG    log_decorator.py Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client_send.py
2022-06-26 19:42:55,948 INFO     task_3_client_send.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, режим работы: send
2022-06-26 19:42:57,990 CRITICAL task_3_client_send.py Не удалось подключиться к серверу 127.0.0.1:7777, конечный компьютер отверг запрос на подключение.
2022-06-26 19:43:06,076 DEBUG    log_decorator.py Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client_send.py
2022-06-26 19:43:06,076 INFO     task_3_client_send.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, режим работы: send
2022-06-26 19:43:06,077 DEBUG    task_3_client_send.py Сформировано presence сообщение для пользователя Guest
2022-06-26 19:43:06,077 DEBUG    log_decorator.py Была вызвана функция create_presence c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client_send.py
2022-06-26 19:43:06,582 DEBUG    task_3_client_send.py Разбор приветственного сообщения от сервера: {'response': 200}
2022-06-26 19:43:06,582 DEBUG    log_decorator.py Была вызвана функция process_response_ans c параметрами ({'response': 200},), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client_send.py
2022-06-26 19:43:06,582 INFO     task_3_client_send.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-06-26 19:43:15,847 DEBUG    task_3_client_send.py Сформирован словарь сообщения: {'action': 'message', 'time': 1656261795.8471882, 'account_name': 'Guest', 'mess_text': 'hellp'}
2022-06-26 19:43:15,847 DEBUG    log_decorator.py Была вызвана функция create_message c параметрами (<socket.socket fd=500, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50184), raddr=('127.0.0.1', 7777)>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client_send.py
2022-06-26 19:43:25,984 DEBUG    task_3_client_send.py Сформирован словарь сообщения: {'action': 'message', 'time': 1656261805.9847345, 'account_name': 'Guest', 'mess_text': 'hell'}
2022-06-26 19:43:25,984 DEBUG    log_decorator.py Была вызвана функция create_message c параметрами (<socket.socket fd=500, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50184), raddr=('127.0.0.1', 7777)>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client_send.py
2022-06-26 20:01:27,487 DEBUG    log_decorator.py Была вызвана функция create_arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 20:01:35,384 INFO     task_3_client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777
2022-06-26 20:01:35,385 DEBUG    log_decorator.py Была вызвана функция create_presence c параметрами ('LoggedUser',), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 20:01:35,887 DEBUG    task_3_client.py Разбор сообщения от сервера: {'response': 200}
2022-06-26 20:01:35,888 DEBUG    log_decorator.py Была вызвана функция process_ans c параметрами ({'response': 200},), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 20:01:35,888 INFO     task_3_client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-06-26 20:01:35,888 DEBUG    task_3_client.py Запущены процессы
2022-06-26 20:01:47,225 DEBUG    task_3_client.py Сформирован словарь сообщения: {'action': 'message', 'sender': 'Guest', 'to': 'LoggedUser', 'time': 1656262907.2254643, 'mess_text': 'Hi'}
2022-06-26 20:01:47,225 INFO     task_3_client.py Отправлено сообщение для пользователя LoggedUser
2022-06-26 20:01:47,226 DEBUG    log_decorator.py Была вызвана функция create_message c параметрами (<socket.socket fd=368, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58708), raddr=('127.0.0.1', 7777)>, 'Guest'), {}.Вызов из модуля __main__.Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive@@@Вызов из функции user_interactive@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 20:01:47,635 ERROR    task_3_client.py Получено некорректное сообщение с сервера: {'action': 'message', 'sender': 'Guest', 'to': 'LoggedUser', 'time': 1656262907.2254643, 'mess_text': 'Hi'}
2022-06-26 20:01:53,544 CRITICAL task_3_client.py Потеряно соединение с сервером.
2022-06-26 20:01:53,545 DEBUG    log_decorator.py Была вызвана функция message_from_server c параметрами (<socket.socket fd=368, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58708), raddr=('127.0.0.1', 7777)>, 'Guest'), {}.Вызов из модуля __main__.Вызов из функции self._bootstrap_inner().Вызов из функции run@@@Вызов из функции run@@@вызов из модуля C:\Python\Python39\lib\threading.py
2022-06-26 20:01:54,088 DEBUG    log_decorator.py Была вызвана функция main c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции <module>@@@Вызов из функции <module>@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 20:16:33,229 DEBUG    log_decorator.py Была вызвана функция create_arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 20:16:39,126 INFO     task_3_client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777
2022-06-26 20:16:39,127 DEBUG    log_decorator.py Была вызвана функция create_presence c параметрами ('LoggedUser',), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 20:16:39,637 DEBUG    task_3_client.py Разбор сообщения от сервера: {'response': 200}
2022-06-26 20:16:39,637 DEBUG    log_decorator.py Была вызвана функция process_ans c параметрами ({'response': 200},), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main@@@Вызов из функции main@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 20:16:39,638 INFO     task_3_client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-06-26 20:16:39,638 DEBUG    task_3_client.py Запущены процессы
2022-06-26 20:16:54,786 DEBUG    task_3_client.py Сформирован словарь сообщения: {'action': 'message', 'sender': 'Guest', 'to': 'LoggedUser', 'time': 1656263814.7862442, 'mess_text': 'Hi'}
2022-06-26 20:16:54,786 INFO     task_3_client.py Отправлено сообщение для пользователя LoggedUser
2022-06-26 20:16:54,787 DEBUG    log_decorator.py Была вызвана функция create_message c параметрами (<socket.socket fd=312, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 63698), raddr=('127.0.0.1', 7777)>, 'Guest'), {}.Вызов из модуля __main__.Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive@@@Вызов из функции user_interactive@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 20:16:55,019 ERROR    task_3_client.py Получено некорректное сообщение с сервера: {'action': 'message', 'sender': 'Guest', 'to': 'LoggedUser', 'time': 1656263814.7862442, 'mess_text': 'Hi'}
2022-06-26 20:17:03,888 DEBUG    log_decorator.py Была вызвана функция create_exit_message c параметрами ('Guest',), {}.Вызов из модуля __main__.Вызов из функции self._bootstrap_inner().Вызов из функции user_interactive@@@Вызов из функции user_interactive@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
2022-06-26 20:17:03,888 INFO     task_3_client.py Завершение работы по команде пользователя.
2022-06-26 20:17:04,402 DEBUG    log_decorator.py Была вызвана функция user_interactive c параметрами (<socket.socket fd=312, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 63698), raddr=('127.0.0.1', 7777)>, 'Guest'), {}.Вызов из модуля __main__.Вызов из функции self._bootstrap_inner().Вызов из функции run@@@Вызов из функции run@@@вызов из модуля C:\Python\Python39\lib\threading.py
2022-06-26 20:17:04,882 DEBUG    log_decorator.py Была вызвана функция main c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции <module>@@@Вызов из функции <module>@@@вызов из модуля C:\Users\zekto\PycharmProjects\Client_server\Task_3\task_3_client.py
